import './globals.css'
import Link from "next/link";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/dashboard">Dashboard</Link>
        </nav>
      </header>
      {children}
      <footer style={{textAlign:"center"}}>
        All rights reserved 2023
      </footer>
      </body>
    </html>
  )
}
